### ISSUE TITLE
:lady_beetle: [Slower than lrzip, same arguments, stuck at 99%]

### ISSUE THREAD

**Issue by DarkCTO** [pete4abw/lrzip-next#129]
### lrzip-next Version

lrzip-next version 0.11.3

### lrzip-next command line

lrzntar -vv -L 9 Absolute\ Supercars\

### What happened?

Using lrzip-next -L 9

Total time: 00:01:18.42
Size: 2,633,370,463 bytes

Using lrzip -L 9
Total time: 00:00:33.57
Size: 2,635,784,356 bytes

Takes 45secs+ longer, stuck 99% for a while.

Side note:
Extraction takes 31:20 to 42:20 (11 minutes) for lrzuntar
43:30 to 45:45 (2 minutes 15 seconds) for lrznuntar

### What was expected behavior?

MD5: 731077b5e40e0527cab7a9b935017780
matches=59726 match_bytes=411253571
literals=87420 literal_bytes=2666419389
true_tag_positives=3729537 false_tag_positives=8395486
inserts=16003294 match 0.154
Compression Ratio: 1.168. Average Compression Speed: 86.324MB/s.
Total time: 00:00:33.57

### Steps to reproduce

lrzntar -L 9 SomeFolder

compares with lrztar -L 9 SomeFolder

### Relevant log output

```shell
The following options are in effect for this COMPRESSION.
Threading is ENABLED. Number of CPUs detected: 16
Detected 33,502,130,176 bytes ram
Nice Value: 19
Show Progress
Max Verbose
Output Filename Specified: /home/kudy/Absolute Supercars (Europe) (En,Fr,De,Es,It)/Absolute Supercars (Europe) (En,Fr,De,Es,It).tar.lrz
Temporary Directory set as: /tmp/
Compression mode is: LZMA. LZ4 Compressibility testing enabled
Compression level 9
RZIP Compression level 9
Initial LZMA Dictionary Size: 134,217,728
MD5 Hashing Used
Heuristically Computed Compression Window: 106 = 10,600MB
Storage time in seconds 1,392,552,880
Shrinking chunk to 3,077,672,960
Succeeded in testing 3,077,672,960 sized mmap for rzip pre-processing
Chunk size: 3,077,672,960
Byte width: 4
Dictionary Size reduced to 100,663,296
Threads reduced to 9
Per Thread Memory Overhead is 1,163,935,744
Succeeded in testing 13,553,094,656 sized malloc for back end compression
Using up to 9 threads to compress up to 341,966,848 bytes each.
Beginning rzip pre-processing phase
hashsize = 4,194,304.  bits = 22. 64MB
Starting sweep for mask 1
Starting sweep for mask 3
Starting sweep for mask 7
Total:  1%  Chunk:  1%
Starting sweep for mask 15
Total:  3%  Chunk:  3%
Starting sweep for mask 31
Total:  6%  Chunk:  6%
Starting sweep for mask 63
Total: 16%  Chunk: 16%
Starting thread 0 to compress 341,966,848 bytes from stream 1
lz4 testing OK for chunk 341,966,848. Compressed size = 98.23% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 0...
Total: 19%  Chunk: 19%
Starting sweep for mask 127
Total: 31%  Chunk: 31%
Starting thread 1 to compress 341,966,848 bytes from stream 1
lz4 testing OK for chunk 341,966,848. Compressed size = 98.99% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 1...
Starting sweep for mask 255
Total: 42%  Chunk: 42%
Starting thread 2 to compress 341,966,848 bytes from stream 1
Total: 43%  Chunk: 43%
lz4 testing FAILED for chunk 341,966,848. Compressed size = 101.00% of test size 335,544,320, 6 Passes
Total: 54%  Chunk: 54%
Starting thread 3 to compress 341,966,848 bytes from stream 1
Total: 55%  Chunk: 55%
lz4 testing FAILED for chunk 341,966,848. Compressed size = 101.00% of test size 335,544,320, 6 Passes
Total: 56%  Chunk: 56%
Starting sweep for mask 511
Total: 66%  Chunk: 66%
Starting thread 4 to compress 341,966,848 bytes from stream 1
Total: 67%  Chunk: 67%
lz4 testing FAILED for chunk 341,966,848. Compressed size = 101.00% of test size 335,544,320, 6 Passes
Total: 79%  Chunk: 79%
Starting thread 5 to compress 341,966,848 bytes from stream 1
lz4 testing OK for chunk 341,966,848. Compressed size = 99.33% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 5...
Total: 90%  Chunk: 90%
Starting thread 6 to compress 341,966,848 bytes from stream 1
Total: 91%  Chunk: 91%
lz4 testing OK for chunk 341,966,848. Compressed size = 98.64% of test size 41,943,040, 3 Passes
Starting lzma backend compression thread 6...
Total: 99%  Chunk: 99%
2,796,202 total hashes -- 4,096 in primary bucket (0.146%)
Malloced 11,167,375,360 for checksum ckbuf
Starting thread 7 to compress 680,346 bytes from stream 0
Starting thread 8 to compress 272,651,453 bytes from stream 1
lz4 testing OK for chunk 680,346. Compressed size = 64.32% of test size 680,346, 1 Passes
Starting lzma backend compression thread 7...
lz4 testing OK for chunk 272,651,453. Compressed size = 99.74% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 8...
Writing initial chunk bytes value 4 at 21
Writing EOF flag as 1
Writing initial header at 27
Compthread 0 seeking to 22 to store length 4
Compthread 0 seeking to 26 to write header
Thread 0 writing 334,165,106 compressed bytes from stream 1
Compthread 0 writing data at 39
Compthread 1 seeking to 35 to store length 4
Compthread 1 seeking to 334,165,145 to write header
Thread 1 writing 335,377,030 compressed bytes from stream 1
Compthread 1 writing data at 334,165,158
Compthread 2 seeking to 334,165,154 to store length 4
Compthread 2 seeking to 669,542,188 to write header
Thread 2 writing 341,966,848 compressed bytes from stream 1
Compthread 2 writing data at 669,542,201
Compthread 3 seeking to 669,542,197 to store length 4
Compthread 3 seeking to 1,011,509,049 to write header
Thread 3 writing 341,966,848 compressed bytes from stream 1
Compthread 3 writing data at 1,011,509,062
Compthread 4 seeking to 1,011,509,058 to store length 4
Compthread 4 seeking to 1,353,475,910 to write header
Thread 4 writing 341,966,848 compressed bytes from stream 1
Compthread 4 writing data at 1,353,475,923
Thread 8: Incompressible block
Compthread 5 seeking to 1,353,475,919 to store length 4
Compthread 5 seeking to 1,695,442,771 to write header
Thread 5 writing 324,770,358 compressed bytes from stream 1
Compthread 5 writing data at 1,695,442,784
Compthread 6 seeking to 1,695,442,780 to store length 4
Compthread 6 seeking to 2,020,213,142 to write header
Thread 6 writing 340,231,206 compressed bytes from stream 1
Compthread 6 writing data at 2,020,213,155
Compthread 7 seeking to 9 to store length 4
Compthread 7 seeking to 2,360,444,361 to write header
Thread 7 writing 274,580 compressed bytes from stream 0
Compthread 7 writing data at 2,360,444,374
Compthread 8 seeking to 2,020,213,151 to store length 4
Compthread 8 seeking to 2,360,718,954 to write header
Thread 8 writing 272,651,453 compressed bytes from stream 1
Compthread 8 writing data at 2,360,718,967
MD5: 731077b5e40e0527cab7a9b935017780

matches=59,726 match_bytes=411,253,571
literals=87,420 literal_bytes=2,666,419,389
true_tag_positives=3,729,537 false_tag_positives=8,395,486
inserts=16,003,294 match 0.154
STDIN - Compression Ratio: 1.169. bpb: 6.845. Average Compression Speed: 37.628MB/s.
Total time: 00:01:18.42
```

### Please provide system details

                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Host: 82K6 Legion 7 16ITHg6 
             `-/ossssssssssssso/.          Kernel: 6.3.9-arch1-1 
           `-/+sssssssssssssssso+:`        Uptime: 18 hours, 55 mins 
         `-:/+sssssssssssssssssso+/.       Packages: 1190 (pacman) 
       `.://osssssssssssssssssssso++-      Shell: bash 5.1.16 
      .://+ssssssssssssssssssssssso++:     Resolution: 1920x1080, 1920x1080, 3840x2160 
    .:///ossssssssssssssssssssssssso++:    WM: i3 
  `:////ssssssssssssssssssssssssssso+++.   Theme: Adwaita [GTK2], Arc-Darker [GTK3] 
`-////+ssssssssssssssssssssssssssso++++-   Icons: Adwaita [GTK2], Qogir [GTK3] 
 `..-+oosssssssssssssssssssssssso+++++/`   Terminal: xfce4-terminal 
   ./++++++++++++++++++++++++++++++/:.     Terminal Font: Source Code Pro 10 
  `:::::::::::::::::::::::::------``       CPU: 11th Gen Intel i9-11980HK (16) @ 4.900GHz 
                                           GPU: NVIDIA GeForce RTX 3080 Mobile / Max-Q 8GB/16GB 
                                           Memory: 8339MiB / 31950MiB

**Comment by pete4abw** [comment]
Thank you for the report, @DarkCTO . What you are observing is a computational error in the block size that has existed in `lrzip` where the actual size of an L9 block is actually smaller than that of L8. The larger the block size sent to the `lzma` backend, the longer it will take. BUT also, the more data the lzma backend gets, the better it will compress!

For example, of you ran `lrzip -L8` on your file, it will take longer. Why? The block size is larger. To verify, run the command `lrzip-next -vvi file.lrz` for your level 9 file. Bet you'll see a whole lot of 10MB block sizes...Like this!

> 57      lzma     18.7%         1,964,723 /     10,485,760        99,225,680 :    101,190,386
58      lzma     19.3%         2,024,027 /     10,485,760       101,190,416 :    103,214,426
59      lzma     17.8%         1,866,466 /     10,485,760       103,214,456 :    105,080,905
60      lzma     17.1%         1,796,152 /     10,485,760       105,080,935 :    106,877,070
61      lzma     16.4%         1,720,089 /     10,485,760       106,877,100 :    108,597,172
62      lzma     18.2%         1,906,213 /     10,485,760       108,597,202 :    110,503,398
63      lzma     15.8%         1,654,436 /     10,485,760       110,503,428 :    112,157,847
64      lzma     12.3%         1,287,033 /     10,485,760       112,157,877 :    113,444,893
65      lzma     11.8%         1,235,493 /     10,485,760       113,444,923 :    114,680,399
66      lzma     14.1%         1,481,555 /     10,485,760       114,680,429 :    116,161,967
67      lzma     14.7%         1,545,113 /     10,485,760       116,161,997 :    121,481,335
68      lzma     15.8%           826,866 /      5,244,299       121,481,365 :              0
>
etc...
Whereas in lrzip-next, the same file will have far fewer blocks. A LOT fewer!
> Block   Comp    Percent        Comp Size /     UComp Size            Offset :           Head
1       lzma     47.5%         8,266,667 /     17,391,605        81,416,543 :              0
Stream: 1
Offset: 40
Block   Comp    Percent        Comp Size /     UComp Size            Offset :           Head
1       lzma     15.4%        40,919,364 /    265,818,112                53 :     40,919,403
2       lzma     15.2%        40,497,100 /    265,818,112        40,919,430 :     89,683,196
3       lzma     15.4%        27,171,067 /    176,153,995        89,683,223 :              0
>
Here you'll see the entire file was compressed using only 4 blocks. Yes, it will be slower, but the compression will almost always be better. Here, for example are the results of a 900+MB Kernel source archive. You will note that lrzip L8 takes longer to compress than lrzip L9 and the archive is actually smaller! This is because the block size of L8 is larger than that of L9.
> 121,352,122  linux-5.8.18.tar.L8.lrzip.lrz, Time: 1:34.560, Block Size: 109,359,787
117,745,499  linux-5.8.18.tar.L8.lrzn.lrz, Time: 1:46.850, Block Size: 140,607,488
122,308,260  linux-5.8.18.tar.L9.lrzip.lrz, Time: 1:18.043, Block Size: *10,485,760*
116,854,335  linux-5.8.18.tar.L9.lrzn.lrz, Time: 2:29.577, Block Size: *265,818,112*
>
You will also notice the time difference between L8 compression diminishes! Please see [this wiki page](https://github.com/pete4abw/lrzip-next/wiki/Chunk-Block-Size-vs-Number-of-Threads) for a lot more information on what I was trying to accomplish here. Thank you again for the report, but it's not a bug!

**Comment by pete4abw** [comment]
Oh yes, one more thing. The "hanging at 99%" is not really hanging. `lrzip-next` is merely waiting for the backend threads to return. The % complete is really inaccurate. It denotes how much of the input file has been read and processed by the RZIP pre-processor. It does not denote how much percent the backend has completed. The ZPAQ compression backend does this for `lrzip` but not for `lrzip-next`, CF #4 . Thank you again for the report!

**Comment by DarkCTO** [comment]
Thanks. Educational read.

Regarding "will almost always be better" compared to lrzip the size some of the times are few megabytes ~10-50 MBs larger, and some of the times are less, so it is not very decisive win (as in always). But faster decompression is decisive (even with those compressed by lrzip L9 so great job on that. Keep in mind I'm compressing game files so binaries.

Also lrznext been giving me a few broken pipe files that resulted in 24Kbs files and I have to redownload those :(

**Comment by pete4abw** [comment]
@DarkCTO , I made a conscious decision early on to make the compression buffer as large as possible. I completely rewrote the logic so that I favored using fewer threads with larger block sizes. This would allow the backend compressors to have more data to work with and _possibly_ yield better compression. `lrzip` will always try and maximize threads, and in the case of level 9 (which is broken in logic) the block size is a meager 10MB. See [this wiki page](https://github.com/pete4abw/lrzip-next/wiki/Chunk-Block-Size-vs-Number-of-Threads)

> Also lrznext been giving me a few broken pipe files that resulted in 21Bytes files and I have to redownload those :(

Would you please open an issue with steps to reproduce so I can look at this as a possible bug? Thank you.
